### ISSUE TITLE
No module named 'evdev'

### ISSUE THREAD

**Issue by stevenb9** [swehner/foos#56]
I'm very sorry to bother you again but when running the ./foos.py I get following output using the default config:

```
pi@raspberrypi:~/Desktop/foos $ ./foos.py 
   INFO - Foos v20160814 starting
   INFO - Blank console
display:2 format:XRGB8888 transform:0 layer:-127 src:0,0,1440,900 dst:0,0,1440,900 cost:889 lbm:0
display:2 format:YUV_UV transform:0 layer:2 src:0,0,1280,720 dst:0,0,128,72 cost:1429 lbm:2048
Patching create surface to fix alpha
   INFO - Display 1440x900@25
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
   INFO - Loading plugins {'sound', 'game', 'league', 'io_debug', 'control', 'score', 'standby', 'leds', 'io_evdev_keyboard', 'menu', 'io_serial'}
Traceback (most recent call last):
  File "./foos.py", line 50, in <module>
    PluginHandler(bus)
  File "/home/pi/Desktop/foos/foos/plugin_handler.py", line 16, in __init__
    self.load(bus)
  File "/home/pi/Desktop/foos/foos/plugin_handler.py", line 23, in load
    module = importlib.import_module('plugins.' + plugin)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/pi/Desktop/foos/plugins/io_evdev_keyboard.py", line 2, in <module>
    import evdev
ImportError: No module named 'evdev'
```
This was fixed doing pip install evdev

```
When enabling the 3 camera plugins in the config i get this output:
pi@raspberrypi:~/Desktop/foos $ ./foos.py 
   INFO - Foos v20160814 starting
   INFO - Blank console
display:2 format:XRGB8888 transform:0 layer:-127 src:0,0,1440,900 dst:0,0,1440,900 cost:889 lbm:0
display:2 format:YUV_UV transform:0 layer:2 src:0,0,1280,720 dst:0,0,128,72 cost:1429 lbm:2048
Patching create surface to fix alpha
   INFO - Display 1440x900@25
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
glGetError 0x500
   INFO - Loading plugins {'score', 'io_serial', 'leds', 'io_debug', 'camera', 'standby', 'league', 'game', 'replay', 'sound', 'motiondetector', 'menu', 'control', 'io_evdev_keyboard'}
  ERROR - No ttyUSB device available
Traceback (most recent call last):
  File "./foos.py", line 50, in <module>
    PluginHandler(bus)
  File "/home/pi/Desktop/foos/foos/plugin_handler.py", line 16, in __init__
    self.load(bus)
  File "/home/pi/Desktop/foos/foos/plugin_handler.py", line 23, in load
    module = importlib.import_module('plugins.' + plugin)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/pi/Desktop/foos/plugins/motiondetector.py", line 3, in <module>
    from inotify_simple import INotify, flags
ImportError: No module named 'inotify_simple'
```
the camera plugins are running after installing an older version of the inotify_simple: pip install inotify_simple==1.0.3

**Comment by swehner** [comment]
All these modules are in the requirements.txt file: did you try to do:
pip3 install -r requirements.txt

That should have installed all requirements

**Comment by stevenb9** [comment]
I did try that command but it would fail when installing Pillow (all other packages were installed), error was something like.. pillow cant find required dependencies for compilation. I manually installed Pillow 2.9.0 which seemed to fix my problem there
